### ISSUE TITLE
thread 'main' panicked at 'capacity overflow' -- with 714bytes file

### ISSUE THREAD

**Issue by PaulGrandperrin** [mvdnes/zip-rs#68]
Hi, I was fuzzing `zip-rs` when it found this panic:
```
thread 'main' panicked at 'capacity overflow', libcore/option.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::option::expect_failed
             at libcore/option.rs:916
   9: <core::option::Option<T>>::expect
             at /checkout/src/libcore/option.rs:302
  10: <alloc::raw_vec::RawVec<T, A>>::allocate_in
             at /checkout/src/liballoc/raw_vec.rs:89
  11: <alloc::raw_vec::RawVec<T>>::with_capacity
             at /checkout/src/liballoc/raw_vec.rs:144
  12: <alloc::vec::Vec<T>>::with_capacity
             at /checkout/src/liballoc/vec.rs:363
  13: <zip::read::ZipArchive<R>>::new
             at /home/paulg/.cargo/git/checkouts/zip-rs-62c959c79813fe27/806147a/src/read.rs:180
  14: zip_read::main::{{closure}}
             at /home/paulg/Projects/fuzz-targets/common/src/lib.rs:758
             at src/bin/zip_read.rs:8
  15: honggfuzz::fuzz
             at /home/paulg/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.18/src/lib.rs:277
  16: zip_read::main
             at src/bin/zip_read.rs:7
  17: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  18: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:305
  19: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:101
  20: std::rt::lang_start_internal
             at libstd/panicking.rs:284
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  21: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  22: main
  23: __libc_start_main
  24: _start
```

here is the code:
```rust
    let reader = std::io::Cursor::new(data);
    let mut archive = if let Ok(x) = zip::ZipArchive::new(reader) { x } else { return; };

    for i in 0..archive.len() {
        use std::io::prelude::*;

        let file = archive.by_index(i).unwrap();
        let _size = file.bytes().count();
    }
```

here is the file
https://drive.google.com/file/d/1WPRI4ed8JDMwQW9BDz-9z_tkqbl93407/view?usp=sharing

**Comment by PaulGrandperrin** [comment]
It also found something else that you might consider an issue.
With this [file](https://drive.google.com/open?id=1Tkk0IdsaifUGXJZlmVBbhdhv1Iyq32CX) (714bytes), a lot of memory will try to be allocated, so much that the process is killed by the fuzzer.

**Comment by mvdnes** [comment]
It was indeed an issue with memory allocation. Thank you for the report! :+1:
