### ISSUE TITLE
Cannot read zip from byte stream

### ISSUE THREAD

**Issue by jcoleman-techempower** [mvdnes/zip-rs#85]
This is more of a question than it is a bug, I'm sure. Given the following code:

```rust
fn index(req: &HttpRequest) -> FutureResponse<HttpResponse> {
  // Get the zip file in the form of bytes
  return req
    .body()
    .limit(512000)
    .from_err()
    .and_then(move |b: Bytes| {
      println!("{:?}", b);

      let mut archive = zip::read::read_zipfile_from_stream(&mut b).unwrap(); // <- error here.

      Ok(HttpResponse::NoContent().into())
    })
    .responder()
}
```

Obviously I do not have an actual stream, but I do have the bytes. How can I create an archive purely from bytes? I've looked into `stdin`, but that doesn't quite fit the bill. I'm trying to read an archive that's being sent in the form of a curl request. Is there some way I can achieve this with my current code as the framework?

**Comment by jcoleman-techempower** [comment]
Could I possibly use [this](https://carllerche.github.io/bytes/bytes/buf/struct.Reader.html)?

**Comment by mvdnes** [comment]
If you have the bytes, then the best course is to wrap it in a [std::io::Cursor](https://doc.rust-lang.org/std/io/struct.Cursor.html). That structure implements `Seek`, so it will be readable using the non-stream functions.

Otherwise you need something that implements `Read`, which your suggestion seems to do.

**Comment by jcoleman-techempower** [comment]
Cool beans! I'll look into Cursor. Thank you for the help

**Comment by jcoleman-techempower** [comment]
Going to reopen this issue, post my code below, and plop the error as well...

<details>
  <summary>Preamble</summary>

  ```rust
  extern crate actix;
  extern crate actix_web;
  extern crate bytes;
  extern crate env_logger;
  extern crate futures;
  extern crate serde;
  #[macro_use] extern crate serde_derive;
  extern crate serde_json;
  extern crate zip;

  pub mod utils;

  use actix::{System, SystemRunner};
  use actix_web::{App, AsyncResponder, FutureResponse, http, HttpMessage, HttpRequest, 
HttpResponse, middleware, Responder, server};
  use bytes::{Buf, Bytes};
  use futures::future::Future;
  use http::{Method, StatusCode};
  use std::env;
  use std::io::{self, Cursor};
  use std::io::prelude::*;
  use utils::{parse_metadata, structs};
  use structs::{ReducedConfig};
  ```
</details>

<details>
  <summary>Rust code</summary>

```rust
fn index(req: &HttpRequest) -> FutureResponse<HttpResponse> {
  // Get the zip file in the form of bytes
  return req
    .body()
    .limit(512000)
    .from_err()
    .and_then(|b: Bytes| {
      // Typically, a zip file is read in, but because we
      // are taking in a byte stream, we will nead to
      // implement Reader. We can also implement Seek in
      // order to use a non-stream function, but using the
      // Cursor API is a more direct approach for this.
      // https://github.com/mvdnes/zip-rs/issues/85

      let reader = Cursor::new(b);
      let mut archive = zip::ZipArchive::new(reader).unwrap();

      let metadata: Vec<ReducedConfig>;
      let results: zip::read::ZipFile<'_>;

      // We can now get the metadata and results by their
      // file names. Because we cannot borrow the same
      // mutable reference more than once, we wrap the
      // first borrow in a closure to let it go out of
      // scope to re-borrow right after. #read_to_string()
      // requires the std::io prelude
      {
        let mut file = archive.by_name("test_metadata.json").unwrap();
        let mut file_contents = String::new();
        file.read_to_string(&mut file_contents).unwrap();

        println!("{:?}", file_contents);

        // Assign to metadata in the upper scope.
        metadata = parse_metadata(&file_contents);
      }

      // Don't do anything with results just yet.
      // results = archive.by_name("results.json").unwrap();

      Ok(HttpResponse::NoContent().into())
    })
    .responder();
}
```

</details>

<details>
  <summary>Error</summary>

```bash
thread 'arbiter:c278514c-40f0-4fac-aa8e-fb772edb2e21:actix-net-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Could not find central directory end")', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
</details>

<details>
  <summary>Backtrace</summary>

```bash
thread 'arbiter:088cba1a-4f42-419f-b976-dbf24e7ae4c1:actix-net-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Could not find central directory end")', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::try::do_call
             at libstd/panicking.rs:326
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: tfb_badges::index::{{closure}}
             at src/main.rs:45
  11: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}::{{closure}}
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/and_then.rs:34
  12: <core::result::Result<T, E>>::map
             at libcore/result.rs:468
  13: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/and_then.rs:33
  14: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:39
  15: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/and_then.rs:32
  16: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  17: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map_err.rs:30
  18: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  19: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/then.rs:32
  20: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  21: <actix_web::pipeline::WaitingResponse<S, H>>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/pipeline.rs:301
  22: <actix_web::pipeline::PipelineState<S, H>>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/pipeline.rs:50
  23: <actix_web::pipeline::Pipeline<S, H> as actix_web::server::handler::HttpHandlerTask>::poll_io
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/pipeline.rs:151
  24: <actix_web::server::h1::Entry<H>>::poll_io
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/server/h1.rs:72
  25: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll_handler
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/server/h1.rs:363
  26: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/server/h1.rs:208
  27: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/server/channel.rs:105
  28: <actix_net::service::map_err::MapErrFuture<A, F, E> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-net-0.1.1/src/service/map_err.rs:92
  29: <actix_net::service::and_then::AndThenFuture<A, B> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-net-0.1.1/src/service/and_then.rs:94
  30: <actix_web::server::acceptor::ServerMessageAcceptorServiceFut<T> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/server/acceptor.rs:378
  31: <futures::future::either::Either<A, B> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/either.rs:35
  32: <futures::future::either::Either<A, B> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/either.rs:35
  33: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map_err.rs:30
  34: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map.rs:30
  35: core::fmt::num::<impl core::fmt::Debug for u64>::fmt
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  36: core::cmp::impls::<impl core::cmp::PartialOrd for isize>::le
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  37: core::cmp::impls::<impl core::cmp::PartialOrd for isize>::le
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  38: futures::task_impl::std::BorrowedUnpark::new
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  39: core::cmp::impls::<impl core::cmp::PartialOrd for isize>::le
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  40: core::cmp::impls::<impl core::cmp::PartialOrd for isize>::le
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
  41: core::cmp::impls::<impl core::cmp::PartialOrd for isize>::le
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  42: <core::cmp::Ordering as core::cmp::PartialEq>::eq
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/scheduler.rs:354
  43: <core::cmp::Ordering as core::cmp::PartialEq>::eq
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/scheduler.rs:333
  44: <core::cmp::Ordering as core::cmp::PartialEq>::eq
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:779
  45: tokio_current_thread::EXECUTOR_ID::__init
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:816
  46: <core::cmp::Ordering as core::cmp::PartialEq>::eq
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:778
  47: core::cmp::impls::<impl core::cmp::PartialOrd for isize>::le
             at libstd/thread/local.rs:294
  48: core::cmp::impls::<impl core::cmp::PartialOrd for isize>::le
             at libstd/thread/local.rs:248
  49: <core::cmp::Ordering as core::cmp::PartialEq>::eq
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:776
  50: <core::cmp::Ordering as core::cmp::PartialEq>::eq
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/scheduler.rs:333
  51: <core::cmp::Ordering as core::cmp::PartialEq>::eq
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:605
  52: alloc::alloc::realloc
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:488
  53: uuid::adapter::core_support::<impl core::fmt::Display for uuid::adapter::HyphenatedRef<'a>>::fmt
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:187
  54: uuid::adapter::core_support::<impl core::fmt::Display for uuid::adapter::HyphenatedRef<'a>>::fmt
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:228
  55: actix::system::CURRENT::__init
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:192
  56: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at libstd/thread/local.rs:294
  57: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at libstd/thread/local.rs:248
  58: actix::system::CURRENT::__init
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:162
  59: uuid::adapter::core_support::<impl core::fmt::Display for uuid::adapter::HyphenatedRef<'a>>::fmt
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:226
  60: <core::cell::BorrowRefMut<'b> as core::ops::drop::Drop>::drop
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/timer/handle.rs:94
  61: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at libstd/thread/local.rs:294
  62: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at libstd/thread/local.rs:248
  63: <core::cell::BorrowRefMut<'b> as core::ops::drop::Drop>::drop
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/timer/handle.rs:81
  64: uuid::adapter::core_support::<impl core::fmt::Display for uuid::adapter::HyphenatedRef<'a>>::fmt
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:219
  65: <alloc::collections::CollectionAllocErr as core::convert::From<core::alloc::LayoutErr>>::from
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/clock/clock.rs:136
  66: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at libstd/thread/local.rs:294
  67: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at libstd/thread/local.rs:248
  68: <alloc::collections::CollectionAllocErr as core::convert::From<core::alloc::LayoutErr>>::from
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/clock/clock.rs:119
  69: uuid::adapter::core_support::<impl core::fmt::Display for uuid::adapter::HyphenatedRef<'a>>::fmt
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:218
  70: <alloc::string::String as core::ops::index::Index<core::ops::range::RangeFull>>::index
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/lib.rs:229
  71: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at libstd/thread/local.rs:294
  72: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at libstd/thread/local.rs:248
  73: <alloc::string::String as core::ops::index::Index<core::ops::range::RangeFull>>::index
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/lib.rs:212
  74: uuid::adapter::core_support::<impl core::fmt::Display for uuid::adapter::HyphenatedRef<'a>>::fmt
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:217
  75: uuid::adapter::core_support::<impl core::fmt::Display for uuid::adapter::HyphenatedRef<'a>>::fmt
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:185
  76: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at /Users/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/arbiter.rs:116
  77: std::sys_common::mutex::Mutex::raw_lock
             at libstd/sys_common/backtrace.rs:136
  78: std::sync::mpsc::sync::Blocker::BlockedReceiver
             at libstd/thread/mod.rs:409
  79: <actix::contextimpl::ContextFlags as core::ops::bit::BitAnd>::bitand
             at libstd/panic.rs:313
  80: std::sync::mpsc::blocking::SignalToken::cast_from_usize
             at libstd/panicking.rs:310
  81: macho_symbol_search
             at libpanic_unwind/lib.rs:103
  82: std::sync::mpsc::blocking::SignalToken::cast_from_usize
             at libstd/panicking.rs:289
  83: <actix::contextimpl::ContextFlags as core::ops::bit::BitAnd>::bitand
             at libstd/panic.rs:392
  84: std::sync::mpsc::sync::Blocker::BlockedReceiver
             at libstd/thread/mod.rs:408
  85: core::num::<impl usize>::max_value
             at liballoc/boxed.rs:646
  86: std::sys_common::thread::start_thread
             at liballoc/boxed.rs:656
             at libstd/sys_common/thread.rs:24
  87: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  88: _pthread_body
  89: _pthread_start
```
</details>

**Comment by jcoleman-techempower** [comment]
I may just need to implement `Seek` instead of `Read`

**Comment by jcoleman-techempower** [comment]
[This implementation doesn't work, by the way](https://docs.rs/zip/0.4.2/zip/read/struct.ZipArchive.html)

**Comment by mvdnes** [comment]
If I had to guess, I think that the zipfile is not complete when calling the parsing function. The index of a zipfile is at the end of the file, so an incomplete file will produce such an error. I see a `.limit(512000)`, so maybe the zipfile you uploaded is larger than 0.5 MB?

**Comment by jcoleman-techempower** [comment]
Oh, Interesting... Yes, the number may be too low. I thought 512000 would be 5MB. That was my mistake. Let's take another stab at this.

**Comment by jcoleman-techempower** [comment]
I upped the limit to `5242880` and I'm still getting this error

**Comment by mvdnes** [comment]
If it is 20KB compressed, then this should be enough. Can you also post some code to setup the listener? I do not know this framework enough to get your example working. Just a simple `main` function with some routing is fine.

**Comment by jcoleman-techempower** [comment]
Sure! Here's my main. I'm using `Actix` for the web server.

```rust
fn main() {
  const LOG_LEVEL: &str = "debug";
  const HOST: &str = "127.0.0.1";
  const PORT: u16 = 8080;

  let uri: String = format!("{}:{}", HOST, PORT);

  env::set_var("RUST_LOG", format!("actix_web={}", LOG_LEVEL));
  // env::set_var("RUST_BACKTRACE", "1");
  env_logger::init();

  let sys: SystemRunner = System::new("app-name");

  server::new(|| App
    ::new()
      .middleware(middleware::Logger::default())
      .resource("/", |r| r.method(Method::POST).f(index))
    )
    .bind(&uri)
    .expect("listen EADDRINUSE")
    .shutdown_timeout(0)
    .start();

  println!("Server started on {}", uri);

  let _ = sys.run();
}
```

**Comment by mvdnes** [comment]
It does seem to work for me. How are you submitting files? I first tried it with curl with just the `-d @file.zip` option, but since a zip contains 0-bytes this truncates it. I had to use `--data-binary @file.zip`.

It may also help to put a `println!("{:?}", b)` before declaring the cursor, to debug if all bytes are actually present.

**Comment by jcoleman-techempower** [comment]
Yeah, so the curl command I did was `curl -d "@data.zip" localhost:8080`. That's very interesting. So, using `--data-binary` is what actually fixes it. I at one point had a debugging print statement, but it was too large and ended up freezing the terminal, so I kinda knew the data was all there.

But I digress. It looks like a simple misuse of the `curl` command. What would this look like without the use of curl? How can I do `--data-binary` when hitting this API with, say, a JavaScript frontend? I guess that's more of a rhetorical question. I'll need to answer that later, but I'm just glad that this issue has been (finally) resolved and I can move on with the project. I really appreciate all your help, @mvdnes . Thank you for remaining patient with me.
